from tkinter import *
root=Tk()
root.geometry('625x350')
root.config(background='red')
emaillabel=Label(root,text='Email').place(x=100,y=20)
passwordlabel=Label(root,text='Password').place(x=79,y=50)
emailentry=Entry(root,width=30).place(x=150,y=20)
passwordentry=Entry(root,show='*',width=30).place(x=150,y=50)
foodlabel=Label(root,text='What food would you like: Chicken sandwich, BLT, Veg sandwich or none?').place(x=120,y=80)
foodentry=Entry(root,width=30).place(x=120,y=110)
foodspinbox=Spinbox(root,from_=0,to=10,bd=0,font=('bahnschrift',10,'normal')).place(x=350,y=111)
drinklabel=Label(root,text='What drink would you like: Cola, Fanta, Orange juice, Water or none?').place(x=120,y=140)
drinkentry=Entry(root,width=30).place(x=120,y=170)
drinkspinbox=Spinbox(root,from_=0,to=10,bd=0,font=('bahnschrift',10,'normal')).place(x=350,y=171)
dessertlabel=Label(root,text='What dessert would you like: Ice cream, Ice lolly, Chocolate cake or none?').place(x=120,y=200)
dessertentry=Entry(root,width=30).place(x=120,y=230)
dessertspinbox=Spinbox(root,from_=0,to=10,bd=0,font=('bahnschrift',10,'normal')).place(x=350,y=231)
submitlabel=Label(root,text='Submit Order').place(x=275,y=260)
submitbutton=Button(root,text='                                                     ',bd=1,background='grey').place(x=230,y=290)
root.mainloop()