from tkinter import *
root=Tk()
root.title('Rock Paper Scissors Game')
gametitle=Label(root,text='Rock Paper Scissors',foreground='grey',font=('bahnschrift',20,'normal')).pack()
outcome=Label(root,text="Let's start the game...",foreground='green',font=('bahnschrift',14,'normal')).pack(pady=20)
frame=Frame(root)
frame.pack()
options=Label(frame,text='Your Options:',font=('bahnschrift',14,'normal'),foreground='grey')
options.grid(row=0,column=0)
score=Label(frame,text='Score:',font=('bahnschrift',14,'normal'),foreground='grey')
score.grid(row=2,column=0)
rockbutton=Button(frame,text='Rock',font=('bahnschrift',14,'normal'),bd=0,background='pink')
rockbutton.grid(row=1,column=1,padx=20)
paperbutton=Button(frame,text='Paper',font=('bahnschrift',14,'normal'),bd=0,background='grey')
paperbutton.grid(row=1,column=2,padx=20)
scissorbutton=Button(frame,text='Scissors',font=('bahnschrift',14,'normal'),bd=0,background='light blue')
scissorbutton.grid(row=1,column=3,padx=20)
yourselection=Label(frame,text='You Selected:',font=('bahnschrift',14,'normal'))
yourselection.grid(row=3,column=1)
computerselection=Label(frame,text='Computer Selected:',font=('bahnschrift',14,'normal'))
computerselection.grid(row=4,column=1)
yourscore=Label(frame,text='Your Score:',font=('bahnschrift',14,'normal'))
yourscore.grid(row=3,column=2)
computerscore=Label(frame,text='Computer Score:',font=('bahnschrift',14,'normal'))
computerscore.grid(row=4,column=2)
mainloop()