from tkinter import *
from tkinter.ttk import *
from tkinter.filedialog import *
root=Tk()
titlelabel=Label(root,text='My Address Book')
titlelabel.grid(row=0,column=0,columnspan=3)
openbutton=Button(root,text='Open')
openbutton.grid(row=0,column=4)
addresslistbox=Listbox(root,width=30,height=13)
addresslistbox.grid(row=2,column=0,columnspan=3,rowspan=5,padx=10,pady=10)
namelabel=Label(root,text='Name:')
namelabel.grid(row=2,column=3)
nameentry=Entry(root,width=25)
nameentry.grid(row=2,column=4,padx=10)
addresslabel=Label(root,text='Address:')
addresslabel.grid(row=3,column=3)
addressentry=Entry(root,width=25)
addressentry.grid(row=3,column=4)
mobilelabel=Label(root,text='Mobile:')
mobilelabel.grid(row=4,column=3)
mobileentry=Entry(root,width=25)
mobileentry.grid(row=4,column=4)
emaillabel=Label(root,text='Email:')
emaillabel.grid(row=5,column=3)
emailentry=Entry(root,width=25)
emailentry.grid(row=5,column=4)
birthdaylabel=Label(root,text='Birthday:')
birthdaylabel.grid(row=6,column=3)
birthdayentry=Entry(root,width=25)
birthdayentry.grid(row=6,column=4)
editbutton=Button(root,text='Edit')
editbutton.grid(row=7,column=0,pady=10)
deletebutton=Button(root,text='Delete')
deletebutton.grid(row=7,column=1)
addbutton=Button(root,text='Add')
addbutton.grid(row=7,column=3)
savebutton=Button(root,text='Save')
savebutton.grid(row=7,column=4)
mainloop()